name: googletest-project
on:
  schedule:
  - cron: '*/5 * * * *'
  push:
    paths-ignore:
      - 'resources/**'
      - 'README.md'

jobs:
  test-project:
    name: Test Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test project with googletest.
        uses: damirjann/hash_array_mapped_trie@main

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: "test-results/**/*.xml"